CREATE TABLE "student" (
  "student_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "email" varchar UNIQUE,
  "password" varchar,
  "department" varchar,
  "year" int,
  "mentor_name" varchar
);

CREATE TABLE "skill_assessment" (
  "assessment_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" int,
  "skills" text[],
  "experience_level" varchar,
  "score" int
);

CREATE TABLE "project_idea" (
  "project_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" int,
  "title" varchar,
  "description" text,
  "domain" varchar,
  "status" varchar
);

ALTER TABLE "skill_assessment" ADD FOREIGN KEY ("student_id") REFERENCES "student" ("student_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "project_idea" ADD FOREIGN KEY ("student_id") REFERENCES "student" ("student_id") DEFERRABLE INITIALLY IMMEDIATE;
